bot:
    prefixes:
        guild:                  ['!', '/']
        direct_message:         ''
    help_prefix:               "bot."
    token:       !REQUIRED_ENV "BOT_TOKEN"
    activity:          "Commands: /help"
    loglevel:          "INFO" # NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL

    cooldowns:
        # Per channel, per tag.
        tags: 60

    clean:
        # Maximum number of messages to traverse for clean commands
        message_limit: 10000

    cogs:
        - coasters

postgresql:
    host: "postgres"
    database: "discordbot"
    user: "discordbot"
    password: "discordbot"

keys:
    captaincoaster: !ENV "CAPTAIN_API_KEY"

urls:
    captain_coaster: !ENV "CAPTAIN_URL"
    captain_cdn: !ENV "CAPTAIN_CDN"
