## RepzBot config file


# Discord Token:
token: "NDcwMTM2MzgzMzgyNjE4MTEy.DjR5_w.xy3XstdJdbRSpzKulOwIdFDf-xA"

# The bots' description:
description: "Bot discord made by Repz using an awesome python lib"

# The bots' command prefix:
prefixes: ['!', '/']

# The bots' activity on Discord:
activity: "Commands: !help"

# The bots' startup extensions.
extensions:
  - cogs.owner
  - cogs.default
  - cogs.vrs
  - embed
  - cogs.dev
  - cogs.error_handler
  - cogs.config

# The bots' admin role. This role is required to execute several critical commands
# like load, unload and so on.
#admin_role: Discord Staff
users_role: Les Pilotes
