## RepzBot config file


# Discord Token:
token: "NDcwMTM2MzgzMzgyNjE4MTEy.DjR5_w.xy3XstdJdbRSpzKulOwIdFDf-xA"

# The bots' description:
description: "Bot discord made by Repz using an awesome python lib"

# The bots' command prefix:
prefixes: ['!', '/']

# The bots' activity on Discord:
activity: "Enfiler les petits enfants"

# The bots' startup extensions. 
# List:
#   - sysinfo_linux (requires humanize, psutil)
#   - sysinfo_windows
#   - figlet (requires pyfiglet)
# Remove sysinfo_linux and figlet if you don't want to install the requirements.
# Also please install: "pip3 install pyfiglet psutil humanize" if you want to run the bot with these extensions.
extensions: ['cogs.owner',
                      'cogs.default',
                      'cogs.vrs',
                      'cogs.embed',
                      'cogs.dev',
                      'cogs.error_handler',
                      'cogs.config']

# The bots' admin role. This role is required to execute several critical commands
# like load, unload and so on.
#admin_role: Discord Staff
users_role: Les Pilotes
