bot:
    prefixes:                  ['!', '/']
    help_prefix:               "bot."
    token:       !REQUIRED_ENV 'BOT_TOKEN'
    default_activity:          "Commands: /help"

    cooldowns:
        # Per channel, per tag.
        tags: 60

    clean:
        # Maximum number of messages to traverse for clean commands
        message_limit: 10000



guild:
    id: 267624335836053506

    channels:
        admins:            &ADMINS        365960823622991872
        news:                             479978283518394378
        skins:             &SKINS         479584029537206272
        team_setups:       &CUSTOM_SETS   464125961018015754

    categories:
        setups:            &SETUPS        242522534526246456

    ignored: [*ADMINS]

    roles:
        admin:             &ADMIN_ROLE    477360039422722059
        pilotes:           &PILOTE_ROLE   409416496733880320
        moderator:         &MOD_ROLE      267629731250176001 # gardé pr l'exemple


filter:

    # What do we filter?
    filter_zalgo:   true
    filter_invites: true
    filter_domains: true
    watch_words:    true
    watch_tokens:   true

    # Filter configuration
    ping_everyone: true  # Ping @everyone when we send a mod-alert?

    guild_invite_whitelist:
        - vywQPxd            # Code Monkeys
        - kWJYurV            # Functional Programming
        - 010z0Kw1A9ql5c1Qe  # Programming: Meme Edition
        - XBGetGp            # STEM

    vanity_url_whitelist:
        - python             # Python Discord

    domain_blacklist:
        - pornhub.com
        - liveleak.com

    word_watchlist:
        - goo+ks*
        - ky+s+
        - gh?[ae]+y+s*
        - ki+ke+s*
        - beaner+s?
        - coo+ns*
        - nig+lets*
        - slant-eyes*
        - towe?l-?head+s*
        - chi*n+k+s*
        - spick*s*
        - kill* +(?:yo)?urself+
        - jew+s*
        - suicide
        - rape
        - (re+)tar+(d+|t+)(ed)?
        - ta+r+d+
        - cunts*

    token_watchlist:
        - fa+g+s*
        - 卐
        - 卍
        - cuck(?!oo+)
        - nigg+(?:e*r+|a+h+?|u+h+)s?
        - fag+o+t+s*

    # Censor doesn't apply to these
    channel_whitelist:
        - *ADMINS
        - *SKINS

    role_whitelist:
        - *ADMIN_ROLE
        - *PILOTE_ROLE
        # - *OWNER_ROLE
        # - *DEVOPS_ROLE # pr l'exemple


keys:
    deploy_bot:  !ENV "DEPLOY_BOT_KEY"
    deploy_site: !ENV "DEPLOY_SITE"
    omdb:        !ENV "OMDB_API_KEY"
    site_api:    !ENV "BOT_API_KEY"
    youtube:     !ENV "AIzaSyCP-v2ZdW13M0fVS01f4NofD185nQQOYCs"


rabbitmq:
    host:          "pdrmq"
    password: !ENV ["RABBITMQ_DEFAULT_PASS", "guest"]
    port:          5672
    username: !ENV ["RABBITMQ_DEFAULT_USER", "guest"]


urls:
    # PyDis site vars
    site:        &DOMAIN       "pythondiscord.com"
    site_api:    &API    !JOIN ["api.", *DOMAIN]
    site_schema: &SCHEMA       "https://"

    site_bigbrother_api:                !JOIN [*SCHEMA, *API, "/bot/bigbrother"]
    site_docs_api:                      !JOIN [*SCHEMA, *API, "/bot/docs"]
    site_facts_api:                     !JOIN [*SCHEMA, *API, "/bot/snake_facts"]
    site_hiphopify_api:                 !JOIN [*SCHEMA, *API, "/bot/hiphopify"]
    site_idioms_api:                    !JOIN [*SCHEMA, *API, "/bot/snake_idioms"]
    site_infractions:                   !JOIN [*SCHEMA, *API, "/bot/infractions"]
    site_infractions_user:              !JOIN [*SCHEMA, *API, "/bot/infractions/user/{user_id}"]
    site_infractions_type:              !JOIN [*SCHEMA, *API, "/bot/infractions/type/{infraction_type}"]
    site_infractions_by_id:             !JOIN [*SCHEMA, *API, "/bot/infractions/id/{infraction_id}"]
    site_infractions_user_type_current: !JOIN [*SCHEMA, *API, "/bot/infractions/user/{user_id}/{infraction_type}/current"]
    site_logs_api:                      !JOIN [*SCHEMA, *API, "/bot/logs"]
    site_logs_view:                     !JOIN [*SCHEMA, *DOMAIN, "/bot/logs"]
    site_names_api:                     !JOIN [*SCHEMA, *API, "/bot/snake_names"]
    site_off_topic_names_api:           !JOIN [*SCHEMA, *API, "/bot/off-topic-names"]
    site_quiz_api:                      !JOIN [*SCHEMA, *API, "/bot/snake_quiz"]
    site_settings_api:                  !JOIN [*SCHEMA, *API, "/bot/settings"]
    site_special_api:                   !JOIN [*SCHEMA, *API, "/bot/special_snakes"]
    site_tags_api:                      !JOIN [*SCHEMA, *API, "/bot/tags"]
    site_user_api:                      !JOIN [*SCHEMA, *API, "/bot/users"]
    site_user_complete_api:             !JOIN [*SCHEMA, *API, "/bot/users/complete"]

    # Env vars
    deploy: !ENV "DEPLOY_URL"
    status: !ENV "STATUS_URL"

    # Misc URLs
    bot_avatar:      "https://raw.githubusercontent.com/discord-python/branding/master/logos/logo_circle/logo_circle.png"
    gitlab_bot_repo: "https://gitlab.com/python-discord/projects/bot"
    omdb:            "http://omdbapi.com"
    paste_service:   "https://paste.pydis.com/{key}"


#anti_spam:
#    # Clean messages that violate a rule.
#    clean_offending: true
#    ping_everyone: true
#
#    punishment:
#        role_id: *MUTED_ROLE
#        remove_after: 600
#
#    rules:
#        attachments:
#            interval: 10
#            max: 3
#
#        burst:
#            interval: 10
#            max: 7
#
#        burst_shared:
#            interval: 10
#            max: 20
#
#        chars:
#            interval: 5
#            max: 3_000
#
#        duplicates:
#            interval: 10
#            max: 3
#
#        discord_emojis:
#            interval: 10
#            max: 20
#
#        links:
#            interval: 10
#            max: 20
#
#        mentions:
#            interval: 10
#            max: 5
#
#        newlines:
#            interval: 10
#            max: 100
#
#        role_mentions:
#            interval: 10
#            max: 3
#
#
reddit:
    request_delay: 60
    subreddits:
        - 'r/iracing'
        - 'r/simracing'
