## RepzBot config file


# Discord Token:
token: ""

# The bots' description:
description: "Discord bot"

# The bots' command prefix:
prefixes: ['!', '/']

# The bots' activity on Discord:
activity: "Commands: /help"

# The bots' startup extensions.
extensions:
  - error_handler
  - owner
  - default
  - vrs
  - embed
  - dev
  - config
  - youtube
  - poll

# The bots' admin role. This role is required to execute several critical commands
# like load, unload and so on.
#admin_role: Discord Staff
users_role: ''


reddit:
  request_delay: 60
  subreddits:
      - 'r/Python'

