version: "3.7"
services:
  discordbot:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: florian987/captainbot
    init: true
    ports:
      - "5000:5000"
    env_file:
      .env.discordbot
    depends_on:
      - "postgres"
  postgres:
    image: postgres:12
    env_file:
      .env.postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
